
name: Generate HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP script
        run: |
          php name: Generate HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP script
        run: |
          php javamessagemq.php > javamessagemq_output.html
          echo "Generated HTML content:"
          cat javamessagemq_output.html

      - name: Commit and push changes
        run: |
          git config user.name 'Your Name'
          git config user.email 'your.email@example.com'
          git add output.html
          git commit -m "Update HTML content"
          git push
.php > javamessagemq_output.html
          echo "Generated HTML content:"
          cat javamessagemq_output.html

      - name: Commit and push changes
        run: |
          git config user.name 'Your Name'
          git config user.email 'your.email@example.com'
          git add output.html
          git commit -m "Update HTML content"
          git push
